### ISSUE TITLE
Replace in selection

### ISSUE THREAD

**Issue by Kristinita** [born2c0de/Incrementor#1]
Hello. You could make function that replacement could be carried out not in all the file but only in that part which I allocated?

Thanks.

**Comment by born2c0de** [comment]
Sure, will try to fix this by the end of the week. Thanks for reporting.

**Comment by Kristinita** [comment]
@born2c0de, we wait. Thank you for your plugin!

**Comment by born2c0de** [comment]
Sorry for the wait @Kristinita. I don't think I understand the issue you're having.
I was under the impression that the replacements were made on the entire file instead of selected regions.
I tried to reproduce your issue today but I can see that it does indeed make replacements only on selected regions.
Can you provide a few steps to reproduce the problem?
Thanks!

**Comment by Kristinita** [comment]
@born2c0de , now replacement in selection work for me. But when I wrote the first post, it's not working for me. Apparently, I was doing something wrong. I'm sorry to trouble you.

**Comment by born2c0de** [comment]
No problem, I'm glad you like the plugin :)
